### PR TITLE
Add `resetChangeset` and `hasEdits`

### PR DESCRIPTION
**Pull request by cherewaty**
I have a UI where I want Save and Cancel buttons that are hidden by default, then show when the form `hasEdits` (not just when the changeset `isDirty`, since an invalid edit to a single field will still cause the changeset to be pristine). When the form is successfully submitted, the Save and Cancel buttons should go away.
- I added `hasEdits`. That's what I use to determine whether the Save and Cancel buttons appear.
- I added `resetChangeset`, set to false by default (current behavior). When set to true, the form's changeset gets replaced by a new one after a successful submit.
- Acceptance test added with a new dummy app route that has this Save/Cancel behavior.

### CODE REVIEW

**Comment by cafreeman** [comment]
@cowboyd I see where you're coming from with regard to exposing changeset like that, but I want to note two things:
- We already yield the entire changeset out in case the user wants to drop down a level and interact with it directly, so it's not exactly hidden
- The use case that Jeffrey is trying to get exposes something that I think is actually pretty useful, and would be significantly more trouble to do from outside x-form itself.

If we can come up with a better name for `resetChangeset` then I think that might be an improvement, but I do think the feature itself is something we want.

**Comment by cowboyd** [comment]
@cafreeman I see. I do feel pretty strongly that our eventual move should be to have the form present its own unified API for working with the changes. In other words, the only api you have to learn is the form's API which we control 100% (even if it's wrapping an API we don't control).

 Haven't we been burned by having a separate, semi-congrous changeset API being exposed before?

That said, how do we get there from here? The catch-22 being we need to make progress here, but at the same time recognizing that this may be an extra piece of api surface that's only required to cover up the fact that we've exposed what will eventually be a private API.

**Comment by cafreeman** [comment]
@cowboyd I see your point. I've been thinking about it more lately and realizing that `x-form` is actually kind of in a grey area at the moment.

It is currently *either* one of two things:
  - A convenient wrapper around `ember-changeset` that just decorates it with some handy utility functions.
- The first pass at a sane approach to immutable data structures that are still very, very Ember-friendly. (In this case, the "form" portion is actually kind of secondary to the bigger "look at how we're building and updating this data structure)

If `x-form` is really the first option, then I think it's ok to make a coherent, but relatively lightweight API and wrap it around `ember-changeset`.

On the other hand, if `x-form` is the second option, then I think the longer term solution is to drop changeset from the mix and build the data structure library that I essentially keep skirting around.

I think the short-term answer is that we `x-form` is a thing that should (at least for now) rely on changeset and we should consider what the MVP of the API really needs to be. I'm anxious for the API to settle a bit so we can actually publicize this thing and get it to a broader audience.

In the long-term, though, I think the `applyChangeset` trick is essentially the kernel of a much bigger idea that I want to keep working on. In many ways an instance of `x-form` is similar to an Immutable.js Record (very much intentional), and I find that I actually tend to want the `x-form` data model far more often than I want an actual form of any kind.

**Comment by cowboyd** [comment]
I'm definitely in the option 2 camp.


which, by the way, I'm dedicated to documentiing this approach.
https://github.com/cowboyd/form-x shhhhhhh..... 🙊

**Comment by cafreeman** [comment]
Gonna go ahead and close this in favor https://github.com/thefrontside/emberx-form/pull/15

**Pull request closed without merging**
